src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 */
class Project
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Title;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="projects")
     */
    private $User;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Badge", mappedBy="project")
     */
    private $badge;

    public function __construct()
    {
        $this->badge = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection|Badge[]
     */
    public function getBadge(): Collection
    {
        return $this->badge;
    }

    public function addBadge(Badge $badge): self
    {
        if (!$this->badge->contains($badge)) {
            $this->badge[] = $badge;
            $badge->setProject($this);
        }

        return $this;
    }

    public function removeBadge(Badge $badge): self
    {
        if ($this->badge->contains($badge)) {
            $this->badge->removeElement($badge);
            // set the owning side to null (unless already changed)
            if ($badge->getProject() === $this) {
                $badge->setProject(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="assets/vendor/css/pages/authentication.css">
            <link rel="stylesheet" href="assets/vendor/fonts/fontawesome.css">
            <link rel="stylesheet" href="assets/vendor/fonts/ionicons.css">
            <link rel="stylesheet" href="assets/vendor/fonts/linearicons.css">
            <link rel="stylesheet" href="assets/vendor/fonts/open-iconic.css">
            <link rel="stylesheet" href="assets/vendor/fonts/pe-icon-7-stroke.css">

            <!-- Core stylesheets -->
            <link rel="stylesheet" href="assets/vendor/css/rtl/bootstrap.css" class="theme-settings-bootstrap-css">
            <link rel="stylesheet" href="assets/vendor/css/rtl/appwork.css" class="theme-settings-appwork-css">
            <link rel="stylesheet" href="assets/vendor/css/rtl/theme-corporate.css" class="theme-settings-theme-css">
            <link rel="stylesheet" href="assets/vendor/css/rtl/colors.css" class="theme-settings-colors-css">
            <link rel="stylesheet" href="assets/vendor/css/rtl/uikit.css">
            <link rel="stylesheet" href="assets/vendor/libs/datatables/datatables.css">
            <link rel="stylesheet" href="assets/vendor/libs/toastr/toastr.css">
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}
            <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
            <script src="{{ asset('bundles/fosjsrouting/js/router.min.js') }}"></script>
            <script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>
            <script src="assets/vendor/libs/toastr/toastr.js"></script>
        {% endblock %}
    </body>
</html>

templates/project.html.twig
{% extends 'base.html.twig' %}

{% block title %}Test{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="../assets/vendor/css/pages/authentication.css">
    <link rel="stylesheet" href="../assets/vendor/fonts/fontawesome.css">
    <link rel="stylesheet" href="../assets/vendor/fonts/ionicons.css">
    <link rel="stylesheet" href="../assets/vendor/fonts/linearicons.css">
    <link rel="stylesheet" href="../assets/vendor/fonts/open-iconic.css">
    <link rel="stylesheet" href="../assets/vendor/fonts/pe-icon-7-stroke.css">

    <!-- Core stylesheets -->
    <link rel="stylesheet" href="../assets/vendor/css/rtl/bootstrap.css" class="theme-settings-bootstrap-css">
    <link rel="stylesheet" href="../assets/vendor/css/rtl/appwork.css" class="theme-settings-appwork-css">
    <link rel="stylesheet" href="../assets/vendor/css/rtl/theme-corporate.css" class="theme-settings-theme-css">
    <link rel="stylesheet" href="../assets/vendor/css/rtl/colors.css" class="theme-settings-colors-css">
    <link rel="stylesheet" href="../assets/vendor/css/rtl/uikit.css">
    <link rel="stylesheet" href="../assets/vendor/libs/datatables/datatables.css">
    <link rel="stylesheet" href="../assets/vendor/libs/toastr/toastr.css">
    <style>.form-control {
            width:500px
        }</style>
{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_row(form.title) }}
    {{ form_row(form.description) }}
    <input type="submit" class="btn btn-primary toto">
    {{ form_end(form) }}
    {% block javascripts %}

    {% endblock %}
{% endblock %}

templates/projects.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="assets/css/style.css" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(180deg, #213b52 0%, #213c54 35%, #204564 100%);
        }
    </style>
{% endblock %}

{% block body %}
    <div>
        <header id="header">
            <div class="container d-flex">

                <div class="logo mr-auto">
                    <img src="assets/img/LOGO_4.png" class="img-responsive" alt="" style="width: 110px; margin-top: -17px;" >
                </div>

                <nav class="nav-menu d-none d-lg-block">
                    <ul>
                        <li class="active"><a href="{{ path('index') }}">Accueil</a></li>
                        <li class="get-started">
                            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                                <a href= "{{ path('app_logout') }}" >Se déconnecter</a>
                            {% else %}
                                <a href= "{{ path('app_login') }}" >Se connecter</a>
                            {% endif %}
                        </li>
                        <li class="get-started">
                            {% if is_granted('ROLE_ADMIN') %}
                                <a href="{{ path('back_default_index') }}" > BACK OFFICE </a>
                            {% endif %}
                        </li>


                    </ul>
                </nav><!-- .nav-menu -->

            </div>
        </header>
        <div>
            <div class="card mb-4" id="card_I" style="margin: 3%">
                <h6 class="card-header" style="background: #a9a8f7">Propositions de projets</h6>
                <div class="card-body">

                    <div class="table-responsive">
                        <table class="datatables-demo table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>Titre</th>
                                <th>Description</th>
                                <th>Choix</th>
                            </tr>
                            </thead>
                            <tbody>
                    {% for project in projects_wait %}
                        <tr>
                            <td>{{ project.title }}</td>
                            <td>{{ project.description }}</td>
                            <td>
                                <a href="{{ path('project_accept',{'id':project.id}) }}"><button class="btn-success">Accepter</button></a>
                                <a href="{{ path('project_refuse',{'id':project.id}) }}"><button class="btn-danger">Refuser</button></a>
                            </td>
                        </tr>
                    {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="card mb-4" id="card_I" style="margin: 3%">
                <h6 class="card-header" style="background: #a9a8f7">projets en cours</h6>
                <div class="card-body">

                    <div class="table-responsive">
                        <table class="datatables-demo table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>Titre</th>
                                <th>Description</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for project in projects_ok %}
                                <tr>
                                    <td>{{ project.title }}</td>
                                    <td>{{ project.description }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


        </div>


    </div>



    {% block javascripts %}
        {{ parent() }}

    {% endblock %}
    {% endblock %}